// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: module/openi.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenIGetTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"client_id"
	ClientId string `protobuf:"bytes,1,opt,name=client_id,proto3" json:"client_id"`
	// @inject_tag: json:"client_secret"
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,proto3" json:"client_secret"`
	// @inject_tag: json:"code"
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	// @inject_tag: json:"grant_type"
	GrantType string `protobuf:"bytes,4,opt,name=grant_type,proto3" json:"grant_type"`
	// @inject_tag: json:"redirect_uri"
	RedirectUri string `protobuf:"bytes,5,opt,name=redirect_uri,proto3" json:"redirect_uri"`
}

func (x *OpenIGetTokenReq) Reset() {
	*x = OpenIGetTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_openi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenIGetTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIGetTokenReq) ProtoMessage() {}

func (x *OpenIGetTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_module_openi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIGetTokenReq.ProtoReflect.Descriptor instead.
func (*OpenIGetTokenReq) Descriptor() ([]byte, []int) {
	return file_module_openi_proto_rawDescGZIP(), []int{0}
}

func (x *OpenIGetTokenReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OpenIGetTokenReq) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OpenIGetTokenReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OpenIGetTokenReq) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *OpenIGetTokenReq) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type OpenIGetTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token"`
	// @inject_tag: json:"token_type"
	TokenType string `protobuf:"bytes,2,opt,name=token_type,proto3" json:"token_type"`
	// @inject_tag: json:"expires_in"
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,proto3" json:"expires_in"`
	// @inject_tag: json:"refresh_token"
	RefreshToken string `protobuf:"bytes,4,opt,name=refresh_token,proto3" json:"refresh_token"`
}

func (x *OpenIGetTokenResp) Reset() {
	*x = OpenIGetTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_openi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenIGetTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIGetTokenResp) ProtoMessage() {}

func (x *OpenIGetTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_module_openi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIGetTokenResp.ProtoReflect.Descriptor instead.
func (*OpenIGetTokenResp) Descriptor() ([]byte, []int) {
	return file_module_openi_proto_rawDescGZIP(), []int{1}
}

func (x *OpenIGetTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OpenIGetTokenResp) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OpenIGetTokenResp) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *OpenIGetTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type OpenIRefreshTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"grant_type"
	GrantType string `protobuf:"bytes,1,opt,name=grant_type,proto3" json:"grant_type"`
	// @inject_tag: json:"refresh_token"
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token"`
}

func (x *OpenIRefreshTokenReq) Reset() {
	*x = OpenIRefreshTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_openi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenIRefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIRefreshTokenReq) ProtoMessage() {}

func (x *OpenIRefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_module_openi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIRefreshTokenReq.ProtoReflect.Descriptor instead.
func (*OpenIRefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_module_openi_proto_rawDescGZIP(), []int{2}
}

func (x *OpenIRefreshTokenReq) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *OpenIRefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type OpenIRefreshTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token"`
	// @inject_tag: json:"token_type"
	TokenType string `protobuf:"bytes,2,opt,name=token_type,proto3" json:"token_type"`
	// @inject_tag: json:"expires_in"
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,proto3" json:"expires_in"`
	// @inject_tag: json:"refresh_token"
	RefreshToken string `protobuf:"bytes,4,opt,name=refresh_token,proto3" json:"refresh_token"`
}

func (x *OpenIRefreshTokenResp) Reset() {
	*x = OpenIRefreshTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_openi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenIRefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIRefreshTokenResp) ProtoMessage() {}

func (x *OpenIRefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_module_openi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIRefreshTokenResp.ProtoReflect.Descriptor instead.
func (*OpenIRefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_module_openi_proto_rawDescGZIP(), []int{3}
}

func (x *OpenIRefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OpenIRefreshTokenResp) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OpenIRefreshTokenResp) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *OpenIRefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type OpenIGetUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token"`
}

func (x *OpenIGetUserReq) Reset() {
	*x = OpenIGetUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_openi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenIGetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIGetUserReq) ProtoMessage() {}

func (x *OpenIGetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_module_openi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIGetUserReq.ProtoReflect.Descriptor instead.
func (*OpenIGetUserReq) Descriptor() ([]byte, []int) {
	return file_module_openi_proto_rawDescGZIP(), []int{4}
}

func (x *OpenIGetUserReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type OpenIGetUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"login"
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"username"
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username"`
	// @inject_tag: json:"avatar_url"
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatar_url,proto3" json:"avatar_url"`
}

func (x *OpenIGetUserResp) Reset() {
	*x = OpenIGetUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_openi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenIGetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIGetUserResp) ProtoMessage() {}

func (x *OpenIGetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_module_openi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIGetUserResp.ProtoReflect.Descriptor instead.
func (*OpenIGetUserResp) Descriptor() ([]byte, []int) {
	return file_module_openi_proto_rawDescGZIP(), []int{5}
}

func (x *OpenIGetUserResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OpenIGetUserResp) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *OpenIGetUserResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OpenIGetUserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OpenIGetUserResp) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_module_openi_proto protoreflect.FileDescriptor

var file_module_openi_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0xae, 0x01, 0x0a,
	0x10, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x61,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x22, 0x9d, 0x01,
	0x0a, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5c, 0x0a,
	0x14, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa1, 0x01, 0x0a, 0x15,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x35, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f,
	0x75, 0x72, 0x6c, 0x42, 0x28, 0x5a, 0x26, 0x70, 0x63, 0x6c, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67,
	0x6f, 0x2d, 0x75, 0x72, 0x63, 0x68, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_module_openi_proto_rawDescOnce sync.Once
	file_module_openi_proto_rawDescData = file_module_openi_proto_rawDesc
)

func file_module_openi_proto_rawDescGZIP() []byte {
	file_module_openi_proto_rawDescOnce.Do(func() {
		file_module_openi_proto_rawDescData = protoimpl.X.CompressGZIP(file_module_openi_proto_rawDescData)
	})
	return file_module_openi_proto_rawDescData
}

var file_module_openi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_module_openi_proto_goTypes = []any{
	(*OpenIGetTokenReq)(nil),      // 0: module.OpenIGetTokenReq
	(*OpenIGetTokenResp)(nil),     // 1: module.OpenIGetTokenResp
	(*OpenIRefreshTokenReq)(nil),  // 2: module.OpenIRefreshTokenReq
	(*OpenIRefreshTokenResp)(nil), // 3: module.OpenIRefreshTokenResp
	(*OpenIGetUserReq)(nil),       // 4: module.OpenIGetUserReq
	(*OpenIGetUserResp)(nil),      // 5: module.OpenIGetUserResp
}
var file_module_openi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_openi_proto_init() }
func file_module_openi_proto_init() {
	if File_module_openi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_module_openi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OpenIGetTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_openi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OpenIGetTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_openi_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OpenIRefreshTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_openi_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OpenIRefreshTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_openi_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OpenIGetUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_openi_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OpenIGetUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_module_openi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_openi_proto_goTypes,
		DependencyIndexes: file_module_openi_proto_depIdxs,
		MessageInfos:      file_module_openi_proto_msgTypes,
	}.Build()
	File_module_openi_proto = out.File
	file_module_openi_proto_rawDesc = nil
	file_module_openi_proto_goTypes = nil
	file_module_openi_proto_depIdxs = nil
}
