// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: module/storage_node.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" xorm:"pk autoincr"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" xorm:"pk autoincr"`
	// @inject_tag: json:"name" xorm:"VARCHAR(64) NOT NULL DEFAULT ” comment('分中心名称')"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" xorm:"VARCHAR(64) NOT NULL DEFAULT ” comment('分中心名称')"`
	// @inject_tag: json:"desc" xorm:"TEXT comment('分中心描述')"
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc" xorm:"TEXT comment('分中心描述')"`
	// @inject_tag: json:"type" xorm:"INT notnull default(0) comment('分中心存储类型，1：ipfs；2：obs；3：minio；...')"
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type" xorm:"INT notnull default(0) comment('分中心存储类型，1：ipfs；2：obs；3：minio；...')"`
	// @inject_tag: json:"property" xorm:"INT notnull default(0) comment('分中心属性，按位标识，置位1则带有该属性，从右向左，第一位标识是否为缓存中心，第二位标识是否为持久化中心')"
	Property int32 `protobuf:"varint,5,opt,name=property,proto3" json:"property" xorm:"INT notnull default(0) comment('分中心属性，按位标识，置位1则带有该属性，从右向左，第一位标识是否为缓存中心，第二位标识是否为持久化中心')"`
	// @inject_tag: json:"status" xorm:"INT notnull default(0) comment('分中心状态，1：在线；2：离线')"
	Status int32 `protobuf:"varint,6,opt,name=status,proto3" json:"status" xorm:"INT notnull default(0) comment('分中心状态，1：在线；2：离线')"`
	// @inject_tag: json:"config" xorm:"TEXT comment('分中心配置信息')"
	Config string `protobuf:"bytes,7,opt,name=config,proto3" json:"config" xorm:"TEXT comment('分中心配置信息')"`
	// @inject_tag: json:"create_time" xorm:"TIMESTAMP notnull created comment('记录创建时间')"
	CreateTime string `protobuf:"bytes,8,opt,name=create_time,proto3" json:"create_time" xorm:"TIMESTAMP notnull created comment('记录创建时间')"`
	// @inject_tag: json:"update_time" xorm:"TIMESTAMP notnull updated comment('记录变更时间')"
	UpdateTime string `protobuf:"bytes,9,opt,name=update_time,proto3" json:"update_time" xorm:"TIMESTAMP notnull updated comment('记录变更时间')"`
	// @inject_tag: json:"delete_time" xorm:"TIMESTAMP NOT NULL DEFAULT '1970-01-01 08:00:01' comment('记录删除时间')"
	DeleteTime string `protobuf:"bytes,10,opt,name=delete_time,proto3" json:"delete_time" xorm:"TIMESTAMP NOT NULL DEFAULT '1970-01-01 08:00:01' comment('记录删除时间')"`
}

func (x *StorageNode) Reset() {
	*x = StorageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_storage_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNode) ProtoMessage() {}

func (x *StorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_module_storage_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNode.ProtoReflect.Descriptor instead.
func (*StorageNode) Descriptor() ([]byte, []int) {
	return file_module_storage_node_proto_rawDescGZIP(), []int{0}
}

func (x *StorageNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageNode) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *StorageNode) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StorageNode) GetProperty() int32 {
	if x != nil {
		return x.Property
	}
	return 0
}

func (x *StorageNode) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StorageNode) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StorageNode) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *StorageNode) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *StorageNode) GetDeleteTime() string {
	if x != nil {
		return x.DeleteTime
	}
	return ""
}

var File_module_storage_node_proto protoreflect.FileDescriptor

var file_module_storage_node_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x22, 0x8b, 0x02, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x42, 0x28, 0x5a, 0x26, 0x70, 0x63, 0x6c, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2d,
	0x75, 0x72, 0x63, 0x68, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_module_storage_node_proto_rawDescOnce sync.Once
	file_module_storage_node_proto_rawDescData = file_module_storage_node_proto_rawDesc
)

func file_module_storage_node_proto_rawDescGZIP() []byte {
	file_module_storage_node_proto_rawDescOnce.Do(func() {
		file_module_storage_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_module_storage_node_proto_rawDescData)
	})
	return file_module_storage_node_proto_rawDescData
}

var file_module_storage_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_module_storage_node_proto_goTypes = []any{
	(*StorageNode)(nil), // 0: module.StorageNode
}
var file_module_storage_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_storage_node_proto_init() }
func file_module_storage_node_proto_init() {
	if File_module_storage_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_module_storage_node_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StorageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_module_storage_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_storage_node_proto_goTypes,
		DependencyIndexes: file_module_storage_node_proto_depIdxs,
		MessageInfos:      file_module_storage_node_proto_msgTypes,
	}.Build()
	File_module_storage_node_proto = out.File
	file_module_storage_node_proto_rawDesc = nil
	file_module_storage_node_proto_goTypes = nil
	file_module_storage_node_proto_depIdxs = nil
}
