// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: module/storage_node.proto

package module

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StorageNode with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StorageNode) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StorageNode with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StorageNodeMultiError, or
// nil if none found.
func (m *StorageNode) ValidateAll() error {
	return m.validate(true)
}

func (m *StorageNode) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Desc

	// no validation rules for Type

	// no validation rules for Property

	// no validation rules for Status

	// no validation rules for Config

	// no validation rules for CreateTime

	// no validation rules for UpdateTime

	// no validation rules for DeleteTime

	if len(errors) > 0 {
		return StorageNodeMultiError(errors)
	}

	return nil
}

// StorageNodeMultiError is an error wrapping multiple validation errors
// returned by StorageNode.ValidateAll() if the designated constraints aren't met.
type StorageNodeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StorageNodeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StorageNodeMultiError) AllErrors() []error { return m }

// StorageNodeValidationError is the validation error returned by
// StorageNode.Validate if the designated constraints aren't met.
type StorageNodeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StorageNodeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StorageNodeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StorageNodeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StorageNodeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StorageNodeValidationError) ErrorName() string { return "StorageNodeValidationError" }

// Error satisfies the builtin error interface
func (e StorageNodeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStorageNode.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StorageNodeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StorageNodeValidationError{}
